inherit_gem:
  retrieva-cop:
    - "config/rubocop.yml"
    # comment unless use rails cops
    - "config/rails.yml"
    # comment unless use rspec cops
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 3.0.1
  # comment unless use rails cops
  TargetRailsVersion: 6.1.3.2

  Exclude:
    - bin/**/*
    - db/**/*
    - config/environments/*
    - config/puma.rb

Style/StringLiterals:
  Enabled: false